apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2am-postgres-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.6  # Replace with a suitable PostgreSQL version
        env:
        - name: POSTGRES_DB
          value: "wso2carbon"  # Set the default database here
        - name: POSTGRES_USER
          value: "gomaa"  # New PostgreSQL user
        - name: POSTGRES_PASSWORD
          value: "gomaa"  # Set the password here
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data  # Mount the PVC to store data persistently
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc  # Reference the PVC created earlier
---
apiVersion: v1
kind: Service
metadata:
  name: wso2am-postgres-db-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Makes the service headless; useful for StatefulSets but optional for simple deployments
